version: '3'
services:
  iamgroot-bot:
    image: ghcr.io/onakrainikoff/tg-iamgroot-bot:1.0
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTIONS: "-Xms128m -Xmx256m -Duser.timezone=Europe/Moscow"
      BOT_USER_NAME: ""
      BOT_TOKEN: ""
      BOT_THREADS_COUNT: 1